version: '3.5'

services:
  codenip-php72-symfony54:
    container_name: codenip-php72-symfony54
    build:
      context: ./docker
      args:
        UID: $U_ID
    volumes:
      - ./:/appdata/www
    ###> XDEBUG 3 ###
    # Use your client IP here
    # Linux: run "ip a | grep docker0"
    # Windows (with WSL2) and Mac: host.docker.internal
    environment:
      XDEBUG_CLIENT_HOST: host.docker.internal
      XDEBUG_CLIENT_PORT: 9003
      #PHP_IDE_CONFIG: serverName=codenip-php72-symfony54
    ports:
      - '1000:8000'
    networks:
      - codenip-php72-symfony54-network
    depends_on:
      - codenip-php72-symfony54-mysql
      

  codenip-php72-symfony54-mysql:
    container_name: codenip-php72-symfony54-mysql
    image: mysql:5.7.37
    ports:
      - '3336:3306'
    environment:
      MYSQL_DATABASE: mysql_symfony
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - codenip-php72-symfony54-mysql-data:/var/lib/mysql
    networks:
      - codenip-php72-symfony54-network
    command:
      [
        'mysqld',
        '--character-set-server=utf8',
        '--collation-server=utf8_unicode_ci'
      ]

###> symfony/mercure-bundle ###
  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: 'GlooudsMercure-JWTKey'
      MERCURE_SUBSCRIBER_JWT_KEY: 'GlooudsMercure-JWTKey'
      # Set the URL of your Symfony project (without trailing slash!) as value of the cors_origins directive
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins * 
    # Comment the following line to disable the development mode
    command: /usr/bin/caddy run -config /etc/caddy/Caddyfile.dev
    networks:
      - codenip-php72-symfony54-network
    volumes:
      - mercure_data:/data
      - mercure_config:/config
###< symfony/mercure-bundle ###

networks:
  codenip-php72-symfony54-network:


volumes:
  codenip-php72-symfony54-mysql-data:

###> symfony/mercure-bundle ###
  mercure_data:
  mercure_config:
###< symfony/mercure-bundle ###
